basePath_upload: "unknow"
basePath_preview: "unknow"
max_size: 100000000
type_reg: "pptx?|docx?|pdf"
spring:
  mail:
    host: smtp.163.com
    port: 465
    username: m17864154913@163.com
    password: forxkasake78647
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      imap:
        ssl:
          socketFactory:
            fallback: false
  data:
    mongodb:
      uri: mongodb://211.87.227.234:27017/zhiku
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhiku?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/freemarker/
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      location: /var/zhiku/temp
mybatis:
  type-aliases-package: com.zhiku.entity
  mapper-locations: com/zhiku/mapper/*.xml
server:
  port: 8080
#logging:
#  level:
#    com.zhiku.*: debug