basePath_upload: "unknow"
basePath_preview: "unknow"
max_size: 100000000
type_reg: "pptx?|docx?|pdf"
spring:
  mail:
    host: smtp.163.com
    port: 465
    username: m17864154913@163.com
    password: forxkasake78647
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
      imap:
        ssl:
          socketFactory:
            fallback: false
  datasource:
    #todo: 临时替换数据库，避免影响上线数据库
    url: jdbc:mysql://cdb-nj2smsfc.bj.tencentcdb.com:10001/zhiku?characterEncoding=utf-8
    username: zhiku
    password: zhiku_123b
#    url: jdbc:mysql://211.87.227.234:3306/zhiku?characterEncoding=utf-8
#    username: root
#    password: Zhiku_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/freemarker/
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      location: /var/zhiku/temp
#  thymeleaf:
#    prefix: /tem/
#    suffix: .jsp
  mvc:
    view:
      prefix: /tem/
      suffix: .jsp
mybatis:
  type-aliases-package: com.zhiku.entity
  mapper-locations: com/zhiku/mapper/*.xml
server:
  port: 18888



#记录文件位置
file_path:
  #访问量记录文件
  visit_statistics: /opt/zhiku/visit_statistics.log
#  visit_statistics: E:\ZhikuFiles\zhiku\visit_statistics.log
  #md课程内容文件储存目录
  md_save: /opt/zhiku/mdFiles
#  md_save: E:/ZhikuFiles
  #上传文件存储目录
  upload_path: /var/zhiku/upload

#logging:
#  level:
#    com.zhiku.*: debug